### ISSUE TITLE
Zip Archive Not Working

### ISSUE THREAD

**Issue by theskyfloor** [masugadesign/link-vault-craft-cms#1]
I get an error when I try to zip an archive and download based on asset ids.

**Comment by ryanmasuga** [comment]
Waiting on some more details for this one:

- Plugin version: 
- Craft version: 
- PHP version: 
- Database driver & version: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by benjaminkohl** [comment]
I deployed a release (3.0.4) that addresses issues with the zipUrl template variable.

**Comment by theskyfloor** [comment]
Great! I will check it out when its pushed to the plug-in store.

**Comment by theskyfloor** [comment]
Fixed!
