### ISSUE TITLE
Is it possible to search downloads in templates

### ISSUE THREAD

**Issue by timprint** [masugadesign/link-vault-craft-cms#16]
I am saving some custom field data with each download (company, job title, country, email etc.).

I am pulling downloads into a template on the front-end like so.
`{% set downloads = craft.linkvault.downloads.limit(25) %}`
It's working great.

I would like to add a search form to the front end template and do something like:
`{% set downloads = craft.linkvault.downloads.search(searchQuery).orderBy('score').limit(25) %}`
which would search the downloads (including the custom fields).
That code doesn't work at the moment.

My question is: **Will search work with LinkVault as it is now or should I be looking for an alternative solution if I need search on custom fields?**

**Comment by benjaminkohl** [comment]
A true element _search_ will not work with Link Vault because it depends on the Craft `searchindex` table and as of Link Vault 3.1.0, I added code to prevent Link Vault elements from getting indexed because it would generate a nasty amount of records on sites that serve a lot of downloads and generally, _searching_ download records isn't very practical.

Prior to 3.1.0, the `dirName` and `fileName` columns got indexed just so the control panel element index page search would match on a supplied filename but even we ended up with client sites that had an unruly number of records in the `searchindex` table just for that bit of control panel functionality. So we removed the Craft element index page from the plugin and added an alternate tool for filtering download records in the control panel that wouldn't rely on the search index.

You can still _query_ custom field attributes using standard field criteria. It just doesn't use Craft's "search" functionality.

**Exact match**
```
{% set downloads = craft.linkvault.downloads.jobTitle('developer').limit(25).all() %}
```

**Partial match**
```
{% set downloads = craft.linkvault.downloads.jobTitle('*dev*').limit(25).all() %}
```

After typing all that, I am now wondering if maybe we could add a setting that allows developers to specify an array of columns that should be indexed for `linkvault_downloads` records. If it is done carefully or if the site in question doesn't get too many download records, it may not be such a bad thing.

**Comment by timprint** [comment]
@benjaminkohl Thanks for taking the time to explain.

Full search of downloads is a '_nice to have_', rather than '_core functionality_', feature on this site. The client doesn't want to spend too much time on it at the moment. I'll see if I can make something work by querying custom fields. That could get us close enough at this stage. 

Indexing specific columns sounds like it could be a nice addition at some point.
