### ISSUE TITLE
Getting a lot of failed search indexes in queue

### ISSUE THREAD

**Issue by lesaff** [masugadesign/link-vault-craft-cms#18]
**Describe the bug**  
I noticed that there are a lot of failed search indexes in my queue. See screenshots. 

**Craft Version & Installed Plugin Version**  
Craft:  3.7.13
Plugin: 
- LinkVault 3.1.7
- Async Queue 2.3.0

**Additional context**  
I am not sure whether this is a much larger issue. See related GH issue https://github.com/craftcms/cms/discussions/9801

----

**Screenshots**

![CleanShot 2021-09-26 at 09 21 16](https://user-images.githubusercontent.com/1151181/134807817-1f6b0157-6f61-43ed-bc91-34d140871587.png)

![CleanShot 2021-09-26 at 09 22 42](https://user-images.githubusercontent.com/1151181/134807844-3bf3b7d3-d142-407f-ba83-b25cb2ca3ed7.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2
 - Browser Firefox
 - Version 92.0

**Comment by benjaminkohl** [comment]
This is very peculiar and is most likely a Craft bug because Link Vault doesn't interact with the Craft search index directly. Craft handles that work behind-the-scenes. Can you send me a sample complete stack trace from one of those errors in the Craft queue.log file? Feel free to obfuscate the system paths for security purposes. I'd like to make sure there isn't something strange about LinkVaultDownload elements that is confusing Craft.

One thing I notice is that the error is occurring because Craft is trying to add a LinkVaultDownload element's "slug" to the search index. That element type does not have titles or slugs so that is very fishy to me.

**Comment by lesaff** [comment]
Closing this issue. The main cause was intermittent database connection issue. As soon as it was handled, all the queues got cleared out.
