### ISSUE TITLE
Pre-Zip assets?

### ISSUE THREAD

**Issue by kevincarpdev** [masugadesign/link-vault-craft-cms#7]
Is there any way to pre-zip contents instead of waiting for a user to follow a link? We have some .zip files that are going to be in the GB's in terms of size so it's awkward for them to wait. Can we trigger the generation on entry creation somehow?

**Comment by benjaminkohl** [comment]
No, there is not currently a way for this to happen with Link Vault and it would take a lot of careful consideration to execute a feature like this because there would be the potential of losing some of the download records for the individual files inside the zip.

A more likely scenario might be caching a generated zip file after it is downloaded the first time but even that would have to be smart enough to refresh if the list of files being zipped changes.
